. /etc/bash_completion

export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[01;33m\]$(__git_ps1)\[\033[01;34m\] \$\[\033[00m\] '

export GOPATH=/vagrant
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

git config --global user.name "Mark Conlin"
git config --global user.email "mark.conlin@gmail.com"


